public class CalendarEvent {

//Variables are set from the CalendarController Class

    public String eventId       {get;set;}
    public String eventTitle    {get;set;}
    public String eventEnd      {get;set;}
    public String eventStart    {get;set;}
    public String eventColor    {get;set;}
    public String url           {get;set;}
    public Boolean allDay       {get;set;}
    public String className     {get;set;}
}